name: trading_app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  auto_route: 3.2.2
  cupertino_icons: 1.0.2
  device_preview: 1.0.0
  easy_localization: 3.0.0
  flutter:
    sdk: flutter
  flutter_screenutil: 5.2.0
  flutter_svg: 1.0.3
  get_it: 7.2.0
  hexcolor: 2.0.6
  injectable: 1.5.3
  logger: 1.1.0

dev_dependencies:
  auto_route_generator: 3.2.1
  build_runner: 2.1.7
  flutter_gen_runner: 4.1.5
  flutter_lints: 1.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: 1.5.3

flutter_gen:
  output: lib/generated/
  line_length: 120

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/dashboard/
    - assets/svg/
    - assets/svg/dashboard/
    - assets/svg/home/
    - assets/translations/
  fonts:
    - family: AktivGrotesk
      fonts:
        - asset: assets/fonts/AktivGroteskCorp-Bold.ttf
          weight: 700
        - asset: assets/fonts/AktivGroteskCorp-Regular.ttf
          weight: 400
